### ISSUE TITLE
#Task #Challenge Make new milestone

### ISSUE THREAD

**Issue by BCFCODE** [Sepehrsalimian/WebStarter#10]
#Task #Challenge @Sepehrsalimian  make new issue with proper name, and assign it to me, ask me a proper help or task and assign it to a milestone for 3 days from now, don't make dummy! make it usefull for your project, this is training to work with milesones

**Comment by Sepehrsalimian** [comment]
It was done last week!
[Streamline project processes](https://github.com/Sepehrsalimian/WebStarter/milestone/2)
with 2 issues.
@BCFCODE
