### ISSUE TITLE
#Task Accept the invitation!

### ISSUE THREAD

**Issue by BCFCODE** [Sepehrsalimian/WebStarter#20]
🚀 You’re in! 🚀

I’ve added you to the BCFCODEwars project! 🎉 Check your invites, accept it, and don’t forget to shoot me a screenshot once you’re in! 📸✨ @Sepehrsalimian 
![image](https://github.com/user-attachments/assets/5e0d0107-a3a6-4829-818e-d35c03302511)

**Comment by Sepehrsalimian** [comment]
Please send me again, link was expired.
@BCFCODE

**Comment by Sepehrsalimian** [comment]
![image](https://github.com/user-attachments/assets/0bdc2e81-a93d-4b2b-868f-360e9c237d65)
Done!
@BCFCODE

**Comment by BCFCODE** [comment]
Good job my boy!
