### ISSUE TITLE
Tasks...

### ISSUE THREAD

**Issue by BCFCODE** [Sepehrsalimian/WebStarter#4]
#Task @Sepehrsalimian This is where I’ll drop your tasks...
Learn these principles: 
![image](https://github.com/user-attachments/assets/945b513a-e597-4f80-95a5-8a3a655a52ba)
![image](https://github.com/user-attachments/assets/18e9afce-64b5-46c3-89c6-e04ce66aa6c0)
![image](https://github.com/user-attachments/assets/5f351c9b-7ee4-4040-8ab6-80f9ebeeee1b)

and let me know when you’ve got them all down!

**Comment by Sepehrsalimian** [comment]
ok!

**Comment by Sepehrsalimian** [comment]
Ok!
@BCFCODE

**Comment by BCFCODE** [comment]
![image](https://github.com/user-attachments/assets/871ab2b5-2750-450b-9a0e-2560612f8a14)

When a task is completed, we can close it in the issue section, with or without adding a comment, like this... #Learning

**Comment by BCFCODE** [comment]
> ![image](https://private-user-images.githubusercontent.com/78473407/365696637-871ab2b5-2750-450b-9a0e-2560612f8a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTMzMzgsIm5iZiI6MTcyNTg5MzAzOCwicGF0aCI6Ii83ODQ3MzQwNy8zNjU2OTY2MzctODcxYWIyYjUtMjc1MC00NTBiLTlhMGUtMjU2MDYxMmY4YTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE0NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Y2EyYTIzYWM0Y2I4ZDFlYTFjOGQxNzFjNTI1MWY0YTEzMGIyZTU4ZTdhZjliYTExMDVmZjkzMGU5ZDZmMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tINXkYH1-xoAp8b2sdh5hop8fOctEiS5f1rfvvB4omc)
> 
> When a task is completed, we can close it in the issue section, with or without adding a comment, like this... #Learning

See our milestone after closing the issue (your task) : 
![image](https://github.com/user-attachments/assets/73981018-f231-4614-8bdb-553a5eb5ab66)
